json_text = '{
"Knowledge": "Nimde3",
"Holy_spirit": "honhonkronkron",
"God": "Awurade/Nyankopon",
"Jesus": "Yesu",
"Lord": "Nyame",
"Miracle": "Nsenkyereni",
"Abroad": "Amanone",
"Wisdom": "Nyansa",
"Idiot": "Ofui",
"Stupid": "Kwasia",
"Fool": "Gyimi",
"Nonsense": "Nsemhunu",
"Adult": "Panin",
"Child": "Akwaraa",
"Group": "Ekuo",
"Food": "Aduane",
"Hunger": "Ek)m",
"Brain": "Adwene",
"Lion": "Gyata",
"Tiger": "Sib)",
"Bird": "Anomaa",
"Bicycle": "Dadeponk)",
"Train": "Ketekye",
"Car": "Ehyen",
"Bed": "Empa",
"Door": "Epono",
"Floor": "Ef)m",
"Morning": "An)pa",
"Noon": "Awia",
"Night": "Anadwo",
"Pillow": "Sumnye3",
"Water": "Nsuo",
"Air": "Nframa",
"Play": "Agor)",
"Clap": "Nsembo",
"Market": "Edwa",
"Machine": "Afide3",
"Knife": "sekan",
"Storey_building": "Abrosan",
"Rag": "Ntomago",
"Spectacle": "Ahwehweniwa",
"Life": "Nkwa",
"Death": "Owuo",
"Pain": ")yaw",
"Mad": "Edam",
"Stone": "Ebo)",
"Foot_wear": "Mpaboa",
"Panty": "Pieto",
"Thousand": "Apem",
"Hundred": ")ha",
"Million": ")pipi",
"Salvation": "Nkwagye3",
"Freedom": "Fahodie",
"Old": "Dada",
"New": "Emono",
"Man": "Papa",
"Mother": "Maame",
"Girl": "Abaayewa",
"Boy": "Abrante3",
"Sugar": "Asikyire",
"Salt": "Enkyene",
"Listen": "Tie",
"Concubine": "Mpena",
"Wife": ")yere",
"Husband": ")kunu",
"Gold": "Sika k)k))",
"Money": "sika",
"Crocodile": "Denkyem",
"Call_me": "Fre me",
"Hold_my_hand": "S) me nsa",
"Sad_story": "Awerehosem",
"Aeroplane": "Ewiamu hyen",
"Box": "Adaka",
"Tied": "Ebr3",
"Why": "aden",
"Please": "m3pacho",
"Go_away": "Fa so hor",
"Lets_go": "y3nko",
"Or": "anaa",
"Dumb": "w\'abon",
"Come": "bra",
"Go": "ko",
"Lets_go_or": "y3nko anaa"
}
'